QuanLySinhVien/QuanLySinhVien/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using QuanLySinhVien.DAL;
using QuanLySinhVien.Models;
using QuanLySinhVien.Services.IRepository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace QuanLySinhVien.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseRepository _courseRepository;
        private readonly IDepartmentRepository _departmentRepository;
        public CourseController(ICourseRepository courseRepository, IDepartmentRepository departmentRepository)
        {
            _courseRepository = courseRepository;
            _departmentRepository = departmentRepository;
        }

        public IActionResult Index()
        {

            //// Method Syntax
            //var allCourse = _context.Courses.Include(x=>x.Department).ToList();

            ////query Syntax
            //var querySyntax = from dept in _context.Departments
            //    join course in _context.Courses on dept.DepartmentId equals course.DepartmentId
            //    select course;

            var allCourses = _courseRepository.CoursesToDepartment();

            return View(allCourses);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var course = _courseRepository.CoursesToDepartment().FirstOrDefault(x => x.Id == id);
            if (course == null && id == 0)
            {
                return NotFound();
            }

            return View(course);
        }

        [HttpGet]
        public IActionResult Create()
        {

            ViewBag.Departments = _departmentRepository.GetAll();

            return View();
        }


        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public IActionResult CreatePost(Course model)
        {
            if (ModelState.IsValid)
            {
                _courseRepository.Add(model);
                return RedirectToAction("Index");
            }

            return View("Create");

        }



        [HttpGet]
        public IActionResult Edit(int id)
        {
            var course = _courseRepository.GetById(id);
            if (course == null)
            {
                return NotFound();
            }
            ViewBag.Departments = _departmentRepository.GetAll();

            return View(course);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Course model)
        {
            if (ModelState.IsValid)
            {
                _courseRepository.Update(model);
                return RedirectToAction("Index");
            }

            return View("Edit");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var course = _courseRepository.GetById(id);
            if (course == null && id == 0)
            {
                return NotFound();
            }

            return View(course);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int id)
        {
            var course = _courseRepository.GetById(id);
            if (course == null && id == 0)
            {
                return NotFound();
            }
            _courseRepository.Delete(course);
            return RedirectToAction("Index");
        }

    }
}

QuanLySinhVien/QuanLySinhVien/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using QuanLySinhVien.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace QuanLySinhVien.Controllers
{

    [Authorize(Policy = "OnlyAdmin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.Select(s => new RoleViewModel
            {
                Id = s.Id,
                Name = s.Name
            }).ToListAsync();

            return View(roles);
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _roleManager.FindByIdAsync(id);
            var model = new RoleViewModel()
            {
                Id = role.Id,
                Name = role.Name
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost, ActionName("Create")]
        public async Task<IActionResult> CreatePost(RoleViewModel model)
        {
            if (model == null)
            {
                return NotFound();
            }
            if (await _roleManager.RoleExistsAsync(model.Name))
            {
                ModelState.AddModelError("", "Name is exist");
            }
            var role = new IdentityRole()
            {
                Name = model.Name
            };

            await _roleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _roleManager.FindByIdAsync(id);
            var model = new RoleViewModel()
            {
                Id = role.Id,
                Name = role.Name
            };
            return View(model);
        }


        [HttpPost, ActionName("Edit")]
        public async Task<IActionResult> EditPost(RoleViewModel model)
        {
            if (model == null)
            {
                return NotFound();
            }

            if (await _roleManager.RoleExistsAsync(model.Name))
            {
                ModelState.AddModelError("", "Name is exist");
            }

            var role = await _roleManager.FindByIdAsync(model.Id);
            role.Name = model.Name;
            role.NormalizedName = model.Name.ToUpper();
            await _roleManager.UpdateAsync(role);
            return RedirectToAction("Index");
        }



        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _roleManager.FindByIdAsync(id);
            var model = new RoleViewModel()
            {
                Id = role.Id,
                Name = role.Name
            };
            return View(model);
        }


        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeletePost(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _roleManager.FindByIdAsync(id);
            await _roleManager.DeleteAsync(role);

            return RedirectToAction("Index");
        }
    }
}

QuanLySinhVien/QuanLySinhVien/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using QuanLySinhVien.Models;
using QuanLySinhVien.Services.IRepository;
using QuanLySinhVien.ViewModels;
using Microsoft.AspNetCore.Mvc;
using ReflectionIT.Mvc.Paging;

namespace QuanLySinhVien.Controllers
{
    public class StudentController : Controller
    {

        private readonly IStudentRepository _studentRepository;
        private readonly IEnrollmentRepository _enrollmentRepository;
        private readonly ICourseRepository _courseRepository;
        public StudentController(IStudentRepository studentRepository, IEnrollmentRepository enrollmentRepository, ICourseRepository courseRepository)
        {
            _studentRepository = studentRepository;
            _enrollmentRepository = enrollmentRepository;
            _courseRepository = courseRepository;
        }

        public IActionResult Index(string sortOrder, string searchString, int pageindex = 1)
        {
            //if (string.IsNullOrEmpty(sortOrder))
            //{
            //    ViewData["sortName"] = "name_desc";
            //}
            //else
            //{
            //    ViewData["sortName"] = "";
            //}
            ViewData["sortName"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["sortByDate"] = sortOrder == "Date" ? "date_desc" : "Date";
            ViewData["currentFilter"] = searchString;
            //if (sortOrder=="Date")
            //{
            //    ViewData["sortByDate"] = "date_desc";
            //}
            //else
            //{
            //    ViewData["sortByDate"] = "Date";
            //}
            var students = _studentRepository.GetStudents();

            if (!string.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.FirstName.ToLower().Contains(searchString.ToLower()) ||
                                               s.LastName.ToLower().Contains(searchString.ToLower()));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    students = students.OrderByDescending(s => s.FirstName);
                    break;
                case "Date":
                    students = students.OrderBy(s => s.EnrollmentDate);
                    break;
                case "date_desc":
                    students = students.OrderByDescending(s => s.EnrollmentDate);
                    break;
                default:
                    students = students.OrderBy(s => s.FirstName);
                    break;

            }

            var model = PagingList.Create(students, 2, pageindex);
            return View(model);
        }

        public IActionResult Details(int id = 0)
        {
            if (id == 0)
            {
                return NotFound();
            }

            ViewBag.Courses = _courseRepository.GetAll();
            var student = _studentRepository.GetById(id);
            var model = new StudentViewModel()
            {
                Student = student,
                Enrollments = _studentRepository.CoursesToStudent(student.Id)
            };

            return View(model);

        }

        public IActionResult AddCourseToStudent(StudentViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Enrollment.StudentId == 0 || model.Enrollment.CourseId == 0)
                {
                    return RedirectToAction("Index");
                }
                _enrollmentRepository.Add(model.Enrollment);

            }

            return RedirectToAction("Details", new { id = model.Enrollment.StudentId });

        }



        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Student model)
        {
            if (ModelState.IsValid)
            {
                _studentRepository.Add(model);
                return RedirectToAction("Index");
            }

            return View("Create");
        }


        public IActionResult Edit(int id)
        {
            var student = _studentRepository.GetById(id);
            if (student == null && id == 0)
            {
                return NotFound();
            }

            return View(student);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public IActionResult EditPost(Student model)
        {
            if (ModelState.IsValid)
            {
                _studentRepository.Update(model);
                return RedirectToAction("Index");
            }

            return View("Edit");
        }

        public IActionResult Delete(int id)
        {
            var student = _studentRepository.GetById(id);
            if (student == null && id == 0)
            {
                return NotFound();
            }

            return View(student);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int id)
        {
            var course = _studentRepository.GetById(id);
            if (course == null && id == 0)
            {

                return NotFound();
            }

            _studentRepository.Delete(course);
            return RedirectToAction("Index");
        }
    }
}

QuanLySinhVien/QuanLySinhVien/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using QuanLySinhVien.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace QuanLySinhVien.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }


        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.Select(s => new UserViewModel
            {
                Id = s.Id,
                Email = s.Email
            }).ToListAsync();
            return View(users);
        }

        public async Task<IActionResult> Details(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            var roles = await _roleManager.Roles.ToListAsync();
            var userRoles = (await _userManager.GetRolesAsync(user)).ToList();  // karwan ==> Admin and user || lewan ==>user

            var model = new UserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                UserInRoles = roles.Select(s => new RoleViewModel()
                {
                    Id = s.Id,
                    Name = s.Name,
                    Select = userRoles.Exists(x => x == s.Name)
                }).ToList()
            };

            return View(model);
        }

        [Authorize(Policy = "OnlyAdmin")]
        [HttpPost, ActionName("Details")]
        public async Task<IActionResult> Update(string id, UserViewModel model)
        {
            var user = await _userManager.Users.FirstOrDefaultAsync(x => x.Id == id);
            var roles = await _roleManager.Roles.ToListAsync();

            foreach (var role in model.UserInRoles)
            {

                if (role.Select)
                {
                    await _userManager.AddToRoleAsync(user, roles.FirstOrDefault(x => x.Id == role.Id)?.Name);
                }
                else
                {
                    await _userManager.RemoveFromRoleAsync(user, roles.FirstOrDefault(x => x.Id == role.Id)?.Name);
                }
            }

            return RedirectToAction("Index");
        }

        //[HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            await _userManager.DeleteAsync(user);

            return RedirectToAction("Index");
        }
    }
}

QuanLySinhVien/QuanLySinhVien/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
<!DOCTYPE html>
@inject SignInManager<IdentityUser> SignInManager;
@inject UserManager<IdentityUser> UserManager;
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body class="container">


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Course" asp-action="Index">Courses <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Student" asp-action="Index">Students <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Department" asp-action="Index">Departments <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" asp-area="" asp-controller="Instructor" asp-action="Index">Instructor <span class="sr-only">(current)</span></a>
                </li>
                @if (User.IsInRole("Admin"))
                {
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Role" asp-action="Index">Roles <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="User" asp-action="Index">Users <span class="sr-only">(current)</span></a>
                    </li>
                }



            </ul>

            @if (!SignInManager.IsSignedIn(User))
            {
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Login">Login <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Register">Register <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            }
            else
            {
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item ">
                        <i class="nav-link">
                            @User.Identity.Name
                        </i>
                    </li>
                    <li class="nav-item active">
                        <form class="nav-link" asp-controller="Account" asp-action="Logout">
                            <input type="submit" class="btn btn-sm btn-outline-success" value="Logout" />
                        </form>
                    </li>
                </ul>
            }
        </div>
    </nav>

    <div>
        @RenderBody()
    </div>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

@*<ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <i class="nav-link">
                @User.Identity.Name
            </i>
        </li>
        <li class="nav-item active">
            <form class="nav-link" asp-controller="Account" asp-action="Logout">
                <input type="submit" class="btn btn-outline-success" value="Logout" />

            </form>
        </li>

    </ul>*@